version: "3.9"

services:
  flask_app:
  container_name: flask_app
  build: .
  ports:
    - "8000:8000"
  environment:
    - DB_URL=postgresql://postgres:postgres@db:5432/postgres
  depends_on:
    - flask_db
  flask_db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_USER=postgres
      - POSTGRESQL_DB=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}